#@TYPE: Machine
#@NAME: Sparrow hawk machine
#@DESCRIPTION: Machine configuration for running sparrow-hawk

SOC_FAMILY = "r8a779g3"
SOC_FAMILY =. "rcar-gen4:"

require conf/machine/include/soc-family.inc

MACHINE_FEATURES = ""
# Add variable to Build Configuration in build log
BUILDCFG_VARS:append = " SOC_FAMILY"

# Configuration for kernel
PREFERRED_PROVIDER_virtual/kernel = "linux-renesas"
KERNEL_IMAGETYPE = "Image"
IMAGE_FSTYPES += " tar.bz2 ext4 wic.gz"
# Device tree
KERNEL_DEVICETREE = "\
    renesas/r8a779g3-sparrow-hawk.dtb \
"
SERIAL_CONSOLES = "921600;ttySC0"

# Configuration for ARM Trusted Firmware
EXTRA_IMAGEDEPENDS += " arm-trusted-firmware"

# u-boot
PREFERRED_VERSION_u-boot = "v2025.10+git%"
EXTRA_IMAGEDEPENDS += " u-boot"
# u-boot configure
UBOOT_MACHINE = "r8a779g3_sparrowhawk_defconfig"

# ipl burning tool
EXTRA_IMAGEDEPENDS += " ipl-burning"

WKS_FILE ?= "rcar-singlepart-noloader.wks"

DEFAULTTUNE ?= "cortexa76"
require conf/machine/include/arm/armv8-2a/tune-cortexa76.inc

