# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "sparrow-hawk"
BBFILE_PATTERN_sparrow-hawk = "^${LAYERDIR}/"
BBFILE_PRIORITY_sparrow-hawk = "6"
LAYERSERIES_COMPAT_sparrow-hawk = "scarthgap whinlatter"

LAYERDEPENDS_sparrow-hawk = "core yocto yoctobsp openembedded-layer meta-python networking-layer"
