name: Build Yocto BSP for Sparrow-hawk
run-name: Build Yocto BSP for Sparrow-hawk
on:
  push:
    branches:
      - 'scarthgap'
      - '*-dev'
      - '*-next'
  workflow_dispatch:

jobs:
  Build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Aggressive cleanup
        # Based on https://github.com/NobuoTsukamoto/my_actions_test/blob/8f1ad38e225730322f196da7d958d0cfd49eca01/.github/workflows/test_contains.yml
        run: |
          df -h
          sudo rm -rf "/home/work/*" || true
          sudo rm -rf "/opt/*" || true
          sudo rm -rf "/usr/local/share/*" || true
          sudo rm -rf "/usr/share/dotnet" || true
          sudo rm -rf "$AGENT_TOOLSDIRECTORY" || true
          sudo rm -rf "/usr/local/lib/android" || true
          sudo rm -rf "/usr/lib/jvm" || true
          sudo rm -rf "/usr/share/swift" || true
          sudo rm -rf "/usr/local/julia*" || true
          sudo rm -rf "/usr/share/kotlinc" || true
          sudo rm -rf "/usr/share/miniconda" || true
          sudo rm -rf "/usr/share/sbt" || true
          sudo rm -rf "/usr/local/sqlpackage" || true
          sudo rm -rf "/usr/bin/yq" || true
          sudo rm -rf "/usr/local/bin/terraform" || true
          sudo rm -rf "/usr/local/bin/stack" || true
          sudo rm -rf "/usr/local/bin/aliyun" || true
          sudo rm -rf "/usr/local/bin/pulumi" || true
          sudo rm -rf "/usr/local/bin/pulumi-language-dotnet" || true
          sudo rm -rf "/usr/local/bin/azcopy" || true
          sudo rm -rf "/usr/local/aws-cli" || true
          sudo rm -rf "/usr/local/bin/bicep" || true
          sudo rm -rf "/usr/local/bin/rebar3" || true
          sudo rm -rf "/usr/local/bin/phpunit" || true
          sudo rm -rf "/usr/local/bin/packer" || true
          sudo rm -rf "/usr/local/bin/bicep" || true
          sudo rm -rf "/usr/local/bin/docker-compose" || true
          sudo rm -rf "/usr/local/bin/minikube" || true
          sudo rm -rf "/usr/local/bin/kustomize" || true
          sudo rm -rf "/usr/local/bin/kubectl" || true
          sudo rm -rf "/usr/local/bin/kind" || true
          sudo rm -rf "/usr/local/bin/helm" || true
          sudo rm -rf "/usr/local/bin/azcopy_11.3.1" || true
          sudo rm -rf "/usr/local/bin/bicep" || true
          sudo rm -rf "/usr/local/bin/.ghcup" || true
          sudo rm -rf "/usr/local/bin/phpunit" || true
          sudo rm -rf "/usr/local/bin/pulumi-*" || true
          sudo rm -rf "/usr/local/bin/oc" || true
          sudo rm -rf "/usr/local/bin/ctest" || true
          sudo rm -rf "/usr/local/bin/cmake-gui" || true
          sudo rm -rf "/usr/local/bin/ccmake" || true
          sudo rm -rf "/usr/local/bin/cpack" || true
          sudo rm -rf "/usr/local/bin/oras" || true
          sudo rm -rf "/home/.dotnet/tools" || true
          sudo rm -rf "/home/linuxbrew" || true
          sudo rm -rf "/home/.nvm" || true
          sudo rm -rf "/home/perflog" || true
          sudo rm -rf "/etc/skel/.dotnet/tools" || true
          sudo rm -rf "/usr/share/apache-maven-3.8.8" || true
          sudo rm -rf "/usr/share/gradle-8.7" || true
          sudo rm -rf "/usr/local/.ghcup" || true
          sudo rm -rf "/usr/bin/composer" || true
          sudo rm -rf "/usr/libexec/docker/cli-plugins" || true
          sudo rm -rf "/usr/bin/docker-credential-ecr-login" || true
          sudo rm -rf "/usr/local/lib/lein" || true
          sudo docker image prune --all --force
          sudo npm uninstall bazel || true
          sudo npm uninstall bazelisk || true
          rustup self uninstall -y
          ls -al /usr/local/share
          df -h
      - name: Remove more packages
        # Based on https://github.com/easimon/maximize-build-space/issues/30
        run: |
          removePackages=`apt list --manual-installed | awk '{print $1}' | sed 's|\(.*\)/.*|\1|' | grep -E -v 'base*|bash|binutils|bsdutils|bzip2|ca-certificates|coreutils|curl|dbus|diffutils|dpkg*|file|findutils|git*|grep|gzip|hostname|init|iproute2|iputils-ping|keyutils|lib*|linux-headers*|linux-image*|lld*|locales|login|lsb-release|make|net-tools|openssh-*|openssl|patchelf|rpm|rsync|session-manager-plugin|shellcheck|ssh|sudo|sysvinit-utils|tar|tcl*|time|tk|tzdata|ubuntu-*|unzip|upx-ucl|walinuxagent|wget|xz-utils|zip*|zsync|apt|dash|ncurses-bin|shim-signed|grub-efi-*|mokutil|sbsigntool|secureboot-db|docker-*|containerd.io' | tr '\n' ' '`
          echo "Removing following userinstalled packages: $removePackages"
          sudo apt-get purge -y $removePackages
          sudo dpkg -r packages-microsoft-prod > /dev/null 2>&1 || true
          sudo apt-get autoremove -y > /dev/null 2>&1 || true
          sudo apt-get autoclean -y > /dev/null 2>&1 || true
          df -h
      - name: Setup package
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential chrpath cpio debianutils diffstat file gawk gcc git iputils-ping \
            libacl1 liblz4-tool locales python3 python3-git python3-jinja2 python3-pexpect \
            python3-pip python3-subunit socat texinfo unzip wget xz-utils zstd device-tree-compiler
          sudo apt-get install -y \
            lvm2
          # Clean up apt
          sudo apt autoremove -y
          sudo apt clean -y
          sudo apt autoclean -y
          # For using --sstate-mirror option
          pip3 install websockets
          df -h

      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 512
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check disk and memory
        run: |
          ls -lh
          df -h
          free -h

      - name: Run build
        run: |
          ./build.sh --sbom --rm-work

      - name: Generate zip archive to release
        run: |
          cd ${GITHUB_WORKSPACE}/build/build-sparrow-hawk/tmp/deploy/images/
          zip -ry deploy_sparrow-hawk.zip sparrow-hawk
          cd ${GITHUB_WORKSPACE}/build/build-sparrow-hawk/tmp/deploy/images/sparrow-hawk
          zip -r ${GITHUB_WORKSPACE}/build/build-sparrow-hawk/tmp/deploy/ipl-burning.zip ./ipl-burning
          cd ${GITHUB_WORKSPACE}/build/build-sparrow-hawk/tmp/deploy
          zip -ry -s 1900m deploy_spdx_split.zip spdx/
          # Prepara kernel deb packages for debian based distribution
          mkdir -p kernel_deb_package
          PKG_LIST="recipe-linux-renesas recipe-linux-fitimage \
                    recipe-arm-trusted-firmware recipe-kernel-module"
          for pkg in ${PKG_LIST}; do
            find ./spdx/sparrow_hawk | grep $pkg | xargs cp -t kernel_deb_package/
            find ./spdx/recipes | grep $pkg | xargs cp -t kernel_deb_package/
          done
          find ./deb/ | grep -e /kernel- -e linux-fitimage | xargs cp -t kernel_deb_package/
          zip -r kernel_deb_package.zip kernel_deb_package

          cd $GITHUB_WORKSPACE

      - name: Prepare release message
        run: |
          OUTPUT="${{ github.workspace }}-release_msg.txt"
          BRANCH="${{ github.ref_name }}"

          # Set Header message
          if [[ "$BRANCH" == *-dev ]]; then
            echo '## Note: This is the latest development build.' > ${OUTPUT}
          else
            echo '## Yocto layer information' > ${OUTPUT}
          fi

          # Body
          cat << 'EOS' >> ${OUTPUT}

          | Layer | Repository | Commit |
          | --- | --- | --- |
          EOS
          for layer in $(ls build/ | grep -v build-); do 
            URL=$(git -C build/${layer}/ remote -v | head -1 | awk '{print $2}')
            COMMIT=$(git -C build/${layer}/ log -n1 --pretty="format:%H")
            echo "| ${layer} | ${URL} | ${COMMIT} |"  >> ${OUTPUT}
          done
          cat << 'EOS' >> ${OUTPUT}

          ### How to use PCIe/USB.
          Please copy correct firmware into /usr/lib/firmware/, then reboot.

          **Note:**
          There is no support/help to get the firmware.
          Please do it at your own risk.
          EOS

      - name: Prepare release tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH="${{ github.ref_name }}"
          if [[ "$BRANCH" == "scarthgap" ]]; then
            # ex.) vYYYY-MM-DD
            echo "TAG_NAME=v$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          elif [[ "$BRANCH" == *-dev ]]; then
            echo "TAG_NAME=dev-latest" >> $GITHUB_ENV
          elif [[ "$BRANCH" == *-next ]]; then
            echo "TAG_NAME=next-release" >> $GITHUB_ENV
          fi

          # Delete old release/tags if exists
          if gh release view "${{ env.TAG_NAME }}" --repo ${{ github.repository }} >/dev/null 2>&1; then
            echo "Deleting old release: ${{ env.TAG_NAME }}"
            gh release delete "${{ env.TAG_NAME }}" --repo ${{ github.repository }} --yes
          fi

      - name: Setup release configuration
        id: prerelease
        run: |
          if [[ "${GITHUB_REF_NAME}" == *-dev ]]; then
            echo "PRERELEASE=true" >> $GITHUB_ENV
            echo "RELEASE_TITLE='Development Latest" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF_NAME}" == *-next ]]; then
            echo "PRERELEASE=true" >> $GITHUB_ENV
            echo "RELEASE_TITLE='Next release candidate" >> $GITHUB_ENV
          else
            echo "PRERELEASE=false" >> $GITHUB_ENV
            echo "RELEASE_TITLE='Release ${{ env.TAG_NAME }}" >> $GITHUB_ENV
          fi

      - name: Create/update release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          target_commitish: ${{ github.ref_name }}
          name: ${{ env.RELEASE_TITLE }}
          draft: false
          prerelease: ${{ env.PRERELEASE }}
          files: |
            ./build/build-sparrow-hawk/tmp/deploy/images/deploy_sparrow-hawk.zip
            ./build/build-sparrow-hawk/tmp/deploy/deploy_spdx_split.z*
            ./build/build-sparrow-hawk/tmp/deploy/kernel_deb_package.zip
            ./build/build-sparrow-hawk/tmp/deploy/ipl-burning.zip
          body_path: ${{ github.workspace }}-release_msg.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

