name: Build test minimal SDK for Sparrow-hawk
run-name: Build test minimal SDK for Sparrow-hawk
on:
  push:
    branches:
      - 'scarthgap'
      - '*-dev'
      - '*-next'
  workflow_dispatch:

jobs:
  Release:
    name: Release
    if: github.repository_owner == 'yhamamachi'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup build envrionment
        uses: ./.github/workflows/setup_build_env

      - name: Run build
        shell: bash
        run: |
          ./build.sh --console --sbom --rm-work --sdk

      - name: Check build results
        shell: bash
        run: |
          #ls -la ./build/build-sparrow-hawk/tmp/deploy/images/sparrow-hawk/*
          ls -la ./build/build-sparrow-hawk/tmp/deploy/sdk/*

