name: Build test using linux-dummy for Sparrow-hawk
run-name: Build test using linux-dummy for Sparrow-hawk
on:
  push:
    branches:
      - 'scarthgap'
      - '*-dev'
      - '*-next'
  workflow_dispatch:

jobs:
  Release:
    name: Release
    if: github.repository_owner == 'rcar-community'
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup build envrionment
        uses: ./.github/workflows/setup_build_env

      - name: Run build
        shell: bash
        run: |
          ./build.sh --console --sbom --rm-work --kernel-version dummy
          # ./build.sh --weston --sbom --rm-work --build-rootfs-only

