name: Build Yocto BSP for Sparrow-hawk
run-name: Build Yocto BSP for Sparrow-hawk
on:
  push:
    branches:
      - '*-dev'
  workflow_dispatch:

jobs:
  Build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@v7
        with:
          root-reserve-mb: 4096
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - uses: actions/checkout@v3
      - name: Setup package
        run: |
          sudo apt update
          sudo apt install -y \
          gawk wget git-core diffstat unzip texinfo gcc-multilib \
          build-essential chrpath socat cpio python3 python3-pip python3-pexpect \
          xz-utils debianutils iputils-ping python3-git python3-jinja2 libegl1-mesa libsdl1.2-dev \
          xterm locales curl vim sudo rsync bc \
          \
          openjdk-8-jdk git-core gnupg flex bison \
          gperf build-essential zip curl zlib1g-dev gcc-multilib ccache \
          g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev \
          libx11-dev lib32z-dev libgl1-mesa-dev libxml2-utils liblz4-tool \
          xsltproc unzip python3-networkx python3-wand liblz4-tool bc \
          apt-transport-https ca-certificates ninja-build \
          ninja-build dosfstools libncurses-dev flex bison \
          screen libncurses-dev ninja-build dosfstools \
          python3-pygit2 python3-venv python3-pyelftools protobuf-compiler gperf pigz \
          zstd simg2img libncurses5 python3-pycryptodome libssl-dev lzop \
          lld libelf-dev dwarves openjdk-11-jdk pigz cmake file device-tree-compiler \

          # Clean up apt
          sudo apt autoremove -y
          sudo apt clean -y
          sudo apt autoclean -y
          pip3 install websockets

      - name: Check disk and memory
        run: |
          ls -lh
          df -h
          free -h

      - name: Setup github config
        run: |
          git config --global user.name "ations-user"
          git config --global user.email "action@github.com"

      - name: Run build
        run: |
          ./build.sh

      - name: Generate zip archive to release
        run: |
          cd ${GITHUB_WORKSPACE}/build/build-sparrow-hawk/tmp/deploy/images/
          zip -ry deploy_sparrow-hawk.zip sparrow-hawk
          cd ${GITHUB_WORKSPACE}/build/build-sparrow-hawk/tmp/deploy/images/sparrow-hawk
          zip -r ${GITHUB_WORKSPACE}/build/build-sparrow-hawk/tmp/deploy/ipl-burning.zip ./ipl-burning
          cd ${GITHUB_WORKSPACE}/build/build-sparrow-hawk/tmp/deploy
          zip -ry -s 1900m deploy_spdx_split.zip spdx/
          # Prepara kernel deb packages for debian based distribution
          mkdir -p kernel_deb_package
          PKG_LIST="recipe-linux-renesas recipe-linux-fitimage \
                    recipe-arm-trusted-firmware recipe-kernel-module"
          for pkg in ${PKG_LIST}; do
            find ./spdx/sparrow_hawk | grep $pkg | xargs cp -t kernel_deb_package/
            find ./spdx/recipes | grep $pkg | xargs cp -t kernel_deb_package/
          done
          find ./deb/ | grep -e /kernel- -e linux-fitimage | xargs cp -t kernel_deb_package/
          zip -r kernel_deb_package.zip kernel_deb_package

          cd $GITHUB_WORKSPACE

      - name: Generate release message
        run: |
          OUTPUT="${{ github.workspace }}-release_msg.txt"
          cat << 'EOS' > ${OUTPUT}
          ## This is the latest development build.

          | Layer | Repository | Commit |
          | --- | --- | --- |
          EOS
          for layer in $(ls build/ | grep -v build-); do 
            URL=$(git -C build/${layer}/ remote -v | head -1 | awk '{print $2}')
            COMMIT=$(git -C build/${layer}/ log -n1 --pretty="format:%H")
            echo "| ${layer} | ${URL} | ${COMMIT} |"  >> ${OUTPUT}
          done
          cat << 'EOS' >> ${OUTPUT}

          ### How to use PCIe/USB.
          Please copy correct firmware into /usr/lib/firmware/, then reboot.

          **Note:**
          There is no support/help to get the firmware.
          Please do it at your own risk.
          EOS

      - name: Delete old release/tags if exists
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME="dev-latest"
          # Release
          if gh release view "$TAG_NAME" --repo ${{ github.repository }} >/dev/null 2>&1; then
            echo "Deleting old release: $TAG_NAME"
            gh release delete "$TAG_NAME" --repo ${{ github.repository }} --yes
          fi
          # Tag
          #if git ls-remote --tags origin | grep "refs/tags/$TAG_NAME$"; then
          #  echo "Deleting old tag: $TAG_NAME"
          #  git push origin :refs/tags/$TAG_NAME
          #fi

      - name: Create or update 'dev-latest' release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: dev-latest
          target_commitish: scarthgap-dev
          name: Development Latest
          draft: false
          prerelease: true
          files: |
            ./build/build-sparrow-hawk/tmp/deploy/images/deploy_sparrow-hawk.zip
            ./build/build-sparrow-hawk/tmp/deploy/deploy_spdx_split.z*
            ./build/build-sparrow-hawk/tmp/deploy/kernel_deb_package.zip
            ./build/build-sparrow-hawk/tmp/deploy/ipl-burning.zip
          body_path: ${{ github.workspace }}-release_msg.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

