name: Build test minimal SDK for Sparrow-hawk
run-name: Build test minimal SDK for Sparrow-hawk
on:
  push:
    branches:
      - 'wrynose'
      - '*-dev'
      - '*-next'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Release:
    name: Release
    if: github.repository_owner == 'yhamamachi'
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup build envrionment
        uses: ./.github/workflows/setup_build_env

      - name: Run build
        shell: bash
        run: |
          # WA for Ubuntu 24.04
          UBUNTU_VERSION=$(cat /etc/os-release | grep VERSION_ID | cut -d'"' -f2)
          if [[ "${UBUNTU_VERSION}" == "24.04" ]]; then
            sudo sysctl -w kernel.unprivileged_userns_clone=1
            sudo apparmor_parser -R /etc/apparmor.d/unprivileged_userns
          fi

          ./build.sh --console --rm-work --sstate-mirror --sdk

