name: Build test weston SDK for Sparrow-hawk
run-name: Build test weston SDK for Sparrow-hawk
on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - "Fetch source code"
    types:
      - completed
jobs:
  Release:
    name: Release
    if: github.repository_owner == 'yhamamachi' && github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup build envrionment
        uses: ./.github/workflows/setup_build_env

      - name: Restore Yocto downloads cache
        uses: actions/cache@v4
        with:
          path: build/build-sparrow-hawk/downloads
          key: yocto-downloads-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            yocto-downloads-${{ runner.os }}-

      - name: Restore Yocto sstate cache
        uses: actions/cache@v4
        with:
          path: build/build-sparrow-hawk/sstate-cache
          key: yocto-sstate-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            yocto-sstate-${{ runner.os }}-

      - name: Run build
        shell: bash
        run: |
          while true; do echo "[keepalive] $(date)"; sleep 60; done &
          ./build.sh -q --weston --sbom --rm-work --sdk

